/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as MySongsRouteImport } from './routes/my-songs'
import { Route as MembersRouteImport } from './routes/members'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityCreatePostRouteImport } from './routes/community/create-post'
import { Route as SongIdIndexRouteImport } from './routes/song/$id/index'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as SongIdEditRouteImport } from './routes/song/$id/edit'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CommunityPostPostIdIndexRouteImport } from './routes/community/post/$postId/index'
import { Route as CommunityPostPostIdEditRouteImport } from './routes/community/post/$postId/edit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const MySongsRoute = MySongsRouteImport.update({
  id: '/my-songs',
  path: '/my-songs',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCreatePostRoute = CommunityCreatePostRouteImport.update({
  id: '/community/create-post',
  path: '/community/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const SongIdIndexRoute = SongIdIndexRouteImport.update({
  id: '/song/$id/',
  path: '/song/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongIdEditRoute = SongIdEditRouteImport.update({
  id: '/song/$id/edit',
  path: '/song/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostPostIdIndexRoute =
  CommunityPostPostIdIndexRouteImport.update({
    id: '/community/post/$postId/',
    path: '/community/post/$postId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityPostPostIdEditRoute = CommunityPostPostIdEditRouteImport.update({
  id: '/community/post/$postId/edit',
  path: '/community/post/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/members': typeof MembersRoute
  '/my-songs': typeof MySongsRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/upload': typeof UploadRoute
  '/community/create-post': typeof CommunityCreatePostRoute
  '/community': typeof CommunityIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/song/$id/edit': typeof SongIdEditRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/song/$id': typeof SongIdIndexRoute
  '/community/post/$postId/edit': typeof CommunityPostPostIdEditRoute
  '/community/post/$postId': typeof CommunityPostPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/members': typeof MembersRoute
  '/my-songs': typeof MySongsRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/upload': typeof UploadRoute
  '/community/create-post': typeof CommunityCreatePostRoute
  '/community': typeof CommunityIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/song/$id/edit': typeof SongIdEditRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/song/$id': typeof SongIdIndexRoute
  '/community/post/$postId/edit': typeof CommunityPostPostIdEditRoute
  '/community/post/$postId': typeof CommunityPostPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/members': typeof MembersRoute
  '/my-songs': typeof MySongsRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/upload': typeof UploadRoute
  '/community/create-post': typeof CommunityCreatePostRoute
  '/community/': typeof CommunityIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/song/$id/edit': typeof SongIdEditRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/song/$id/': typeof SongIdIndexRoute
  '/community/post/$postId/edit': typeof CommunityPostPostIdEditRoute
  '/community/post/$postId/': typeof CommunityPostPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/members'
    | '/my-songs'
    | '/playlists'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/upload'
    | '/community/create-post'
    | '/community'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/song/$id/edit'
    | '/profile/$userId'
    | '/song/$id'
    | '/community/post/$postId/edit'
    | '/community/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/members'
    | '/my-songs'
    | '/playlists'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/upload'
    | '/community/create-post'
    | '/community'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/song/$id/edit'
    | '/profile/$userId'
    | '/song/$id'
    | '/community/post/$postId/edit'
    | '/community/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/members'
    | '/my-songs'
    | '/playlists'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/upload'
    | '/community/create-post'
    | '/community/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/song/$id/edit'
    | '/profile/$userId/'
    | '/song/$id/'
    | '/community/post/$postId/edit'
    | '/community/post/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  MembersRoute: typeof MembersRoute
  MySongsRoute: typeof MySongsRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UploadRoute: typeof UploadRoute
  CommunityCreatePostRoute: typeof CommunityCreatePostRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  SongIdEditRoute: typeof SongIdEditRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
  SongIdIndexRoute: typeof SongIdIndexRoute
  CommunityPostPostIdEditRoute: typeof CommunityPostPostIdEditRoute
  CommunityPostPostIdIndexRoute: typeof CommunityPostPostIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-songs': {
      id: '/my-songs'
      path: '/my-songs'
      fullPath: '/my-songs'
      preLoaderRoute: typeof MySongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/create-post': {
      id: '/community/create-post'
      path: '/community/create-post'
      fullPath: '/community/create-post'
      preLoaderRoute: typeof CommunityCreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$id/': {
      id: '/song/$id/'
      path: '/song/$id'
      fullPath: '/song/$id'
      preLoaderRoute: typeof SongIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$id/edit': {
      id: '/song/$id/edit'
      path: '/song/$id/edit'
      fullPath: '/song/$id/edit'
      preLoaderRoute: typeof SongIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/post/$postId/': {
      id: '/community/post/$postId/'
      path: '/community/post/$postId'
      fullPath: '/community/post/$postId'
      preLoaderRoute: typeof CommunityPostPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/post/$postId/edit': {
      id: '/community/post/$postId/edit'
      path: '/community/post/$postId/edit'
      fullPath: '/community/post/$postId/edit'
      preLoaderRoute: typeof CommunityPostPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  MembersRoute: MembersRoute,
  MySongsRoute: MySongsRoute,
  PlaylistsRoute: PlaylistsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UploadRoute: UploadRoute,
  CommunityCreatePostRoute: CommunityCreatePostRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  SongIdEditRoute: SongIdEditRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
  SongIdIndexRoute: SongIdIndexRoute,
  CommunityPostPostIdEditRoute: CommunityPostPostIdEditRoute,
  CommunityPostPostIdIndexRoute: CommunityPostPostIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
